menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'projects', url: '/projects'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Tzu-Yu Hsu PhD', title: 'Associate Professor', department: 'Graduate Institute of Mind, Brain and Consciousness', institution: 'Taipei Medical University', institution_address: 'No. 250, Wuxing St, Xinyi District, Taipei City', email: 'tzuyu.hsu@tmu.edu.tw', office: '12F, TMU Daan campus', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Antonio Martin', title: 'Postdoc', department: 'Graduate Institute of Mind, Brain and Consciousness', institution: 'Taipei Medical University', email: 'antonio@tmu.edu.tw', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Paul Z. Cheng', title: 'PhD student', department: 'Graduate Institute of Mind, Brain and Consciousness', institution: 'Taipei Medical University', email: 'paul.z.cheng@tmu.edu.tw', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}
- {name: 'Ko-ping Chou', title: 'Research Assistant', department: 'Graduate Institute of Mind, Brain and Consciousness', institution: 'Taipei Medical University', email: 'koping14916@tmu.edu.tw', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}
- {name: 'Charlie Chiang', title: 'Administrative Assistant', department: 'Graduate Institute of Mind, Brain and Consciousness', institution: 'Taipei Medical University', email: 'charlie55@tmu.edu.tw', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

projects:
- {name: 'Self-relted processes & brain', url: 'vector-calculus'}
- {name: 'Visual awareness in consciousness & brain', url: 'quantum-mechanics'}
- {name: 'Time process & brain', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Dr. Tzuyu Hsu', title: 'Associate Professor', institute: 'Graduate Institute of Mind, Brain and Consciousness', institution: 'Taipei Medical University', institution_address: 'No. 250, Wuxing St, Xinyi District, Taipei City', email: 'tzuyu.hsu@tmu.edu.tw', image: 'assets/img/contact.jpg'}
